-- EXAMSAARTHI V2 DATABASE SCHEMA
-- 
-- DEPRECATED: do not execute this file.
--
-- The authoritative database definition is the ordered migration set:
--   supabase/migrations/00000_schema.sql
--   supabase/migrations/00001_multilingual_questions.sql
--   supabase/migrations/00002_demo_exam_data.sql
--   supabase/migrations/00003_secure_answers.sql
--   supabase/migrations/00004_exam_analytics.sql
--   supabase/migrations/00005_vision_accessibility.sql
--   supabase/migrations/00006_harden_exam_security.sql
--   supabase/migrations/00006_practice_and_difficulty.sql
--   supabase/migrations/00007_preferences_and_consent.sql
--   supabase/migrations/00008_lock_exam_session_inserts.sql
--   supabase/migrations/00009_practice_question_roster.sql
--   supabase/migrations/00010_session_integrity.sql
--   supabase/migrations/00011_harden_audit_logs.sql
--   supabase/migrations/00012_practice_subjects.sql
--   supabase/migrations/00013_content_metadata.sql
--   supabase/migrations/00014_questions_roster_rls.sql
--
-- This file previously contained the pre-security schema and could recreate
-- the removed public questions.correct_answer_index column. It is intentionally
-- kept as a SQL-comment-only marker so nobody can accidentally apply the stale
-- schema to a current Supabase project.
